# Generated by Django 6.0 on 2026-01-19 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_register', '0002_rename_name_customer_first_name_customer_second_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='second_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_type',
            field=models.CharField(choices=[('home', 'Home Delivery'), ('pickup', 'Store Pickup')], default='home', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, default='no address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Enter valid Pakistani number (03XXXXXXXXX)', regex='^03\\d{9}$')]),
        ),
    ]
