# Generated by Django 5.2.7 on 2026-01-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_register', '0003_remove_customer_password_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
