# Generated by Django 5.2.7 on 2026-01-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Customer',
        ),
    ]
