# Generated by Django 5.2.7 on 2026-01-27 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_user_cart_created_at'),
        ('user_register', '0003_remove_customer_second_name_customer_delivery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_register.customer'),
        ),
    ]
