# Generated by Django 5.2.7 on 2026-01-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_order_user_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('order_dispatched', 'Order Dispatched'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
